"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SETTING_KEYS = void 0;
exports.SETTING_KEYS = {
    // Existing brain settings
    OPENAI_API_KEY: 'OPENAI_API_KEY',
    ANTHROPIC_API_KEY: 'ANTHROPIC_API_KEY',
    DEEPSEEK_API_KEY: 'DEEPSEEK_API_KEY',
    USE_LOCAL_BRAIN: 'USE_LOCAL_BRAIN',
    OLLAMA_HOST: 'OLLAMA_HOST',
    OLLAMA_MODEL: 'OLLAMA_MODEL',
    DEFAULT_BRAIN_MODEL: 'DEFAULT_BRAIN_MODEL',
    BRAIN_TEMPERATURE: 'BRAIN_TEMPERATURE',
    BRAIN_SYSTEM_PROMPT: 'BRAIN_SYSTEM_PROMPT',
    TTS_VOICE_URI: 'TTS_VOICE_URI',
    EDGE_TTS_VOICE: 'EDGE_TTS_VOICE',
    // New channel settings (JSON)
    OPENCLAW_CHANNELS_CONFIG: 'OPENCLAW_CHANNELS_CONFIG',
    OPENCLAW_CHANNELS_ENABLED: 'OPENCLAW_CHANNELS_ENABLED', // boolean
    // Skill settings (JSON)
    OPENCLAW_SKILLS_CONFIG: 'OPENCLAW_SKILLS_CONFIG',
    // Cron/monitoring settings (JSON)
    OPENCLAW_CRON_JOBS: 'OPENCLAW_CRON_JOBS',
    OPENCLAW_MONITORING_ENABLED: 'OPENCLAW_MONITORING_ENABLED', // boolean
    // Chat history settings
    CHAT_HISTORY_WINDOW_SIZE: 'CHAT_HISTORY_WINDOW_SIZE', // number, default 10
    CHAT_ENABLE_SUMMARIZATION: 'CHAT_ENABLE_SUMMARIZATION', // boolean
    CHAT_MAX_TOKENS: 'CHAT_MAX_TOKENS', // number
};
